"""
Master G-code generator.

Takes a list of PlacedPart objects (each with a parsed GcodePart and placement
info) and produces a single merged .nc file following the order-of-operations
merge rules and nearest-neighbor travel sort from the spec.
"""
import re
from datetime import datetime
from typing import Dict, List, Optional, Tuple

from collision import PlacedPart

# ── compiled patterns ─────────────────────────────────────────────────────────

_IJ = re.compile(r"([IJ])([+-]?\d*\.?\d+)")
_N_CODE = re.compile(r"^N\d+\s*")
_TOOL_CMT = re.compile(r"\(\s*Tool:\s*(.+?)\)", re.IGNORECASE)
_SPINDLE = re.compile(r"\bM03\b.*\bS(\d+)\b", re.IGNORECASE)


# ── public entry point ────────────────────────────────────────────────────────

def generate_master_gcode(placements: List[PlacedPart], settings: Dict) -> str:
    """
    Build a merged master G-code string from a list of placed parts.

    Order of operations:
      Walk pass indices 0, 1, 2... across all parts.
      At each index, group by tool number.
      Consecutive blocks with the same tool are merged (no tool change inserted).
      Within each merged block, segments are sorted by nearest-neighbor to
      minimise rapid-travel distance without violating per-part operation order.
    """
    adv = settings["advanced"]
    rail_w = float(adv["rail_width_mm"])
    bed_x = float(adv["bed_x_mm"])
    park_x = float(adv.get("park_x", 0.0))
    park_y = float(adv.get("park_y", 3048.0))
    job_name = settings.get("job_name", "master_job")
    safe_z_info = settings.get("job_safe_z") or {}
    job_safe_z = float(safe_z_info.get("value") or adv.get("safe_z_clearance_mm", 25.4))
    safe_z_driver = safe_z_info.get("driven_by") or ""

    filenames = [p.part.filename for p in placements]
    all_tools: List[str] = []
    for p in placements:
        for gp in p.part.passes:
            if gp.tool_number not in all_tools:
                all_tools.append(gp.tool_number)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    out: List[str] = []
    _n = [10]

    def N(line: str) -> str:
        n = _n[0]
        _n[0] += 10
        return f"N{n} {line}"

    # ── file header (no line numbers) ─────────────────────────────────────────
    out += [
        "(MASTER JOB - Generated by CNC Nest Tool)",
        f"(Date: {now})",
        f"(Job: {job_name})",
        f"(Parts: {', '.join(filenames)})",
        f"(Instances: {len(placements)}  Tools: {', '.join(all_tools)})",
        f"(Safe Z: {job_safe_z}mm — driven by {safe_z_driver})",
        "",
        N("G00 G17 G71 G40 G49 G80 G90"),
        N("G21 (metric)"),
        N("G54"),
        N("G53 Z0"),
    ]

    # ── tool blocks ───────────────────────────────────────────────────────────
    blocks = _build_blocks(placements, rail_w, bed_x)

    for block_num, block in enumerate(blocks, start=1):
        tool = block["tool"]
        h_num = re.sub(r"\D", "", tool)  # "T2" → "2"
        segs = _nearest_neighbor_sort(block["segments"])

        out += [
            "",
            f"( ---- {tool} pass {block_num} ---- )",
            N(f"{tool} M06"),
        ]
        if block["description"]:
            out.append(N(f"({block['description']})"))
        out += [
            N(f"G43 H{h_num} Z{job_safe_z:.4f}"),
            N(f"M03 S{block['spindle_speed']}"),
        ]
        for seg in segs:
            for ln in seg:
                if ln.strip():
                    out.append(N(ln.strip()))
        out += [
            N("G53 G49 Z0"),
            N("M05"),
        ]

    # ── park and end ──────────────────────────────────────────────────────────
    out += [
        "",
        "( ---- park ---- )",
        N(f"G00 G53 X{park_x:.4f} Y{park_y:.4f} M05"),
        N("M30"),
        "%",
    ]

    return "\n".join(out) + "\n"


# ── block building ────────────────────────────────────────────────────────────

def _build_blocks(placements: List[PlacedPart], rail_w: float, bed_x: float) -> list:
    """
    Produce an ordered list of tool blocks from all placements.

    Walk pass indices 0..max in order. At each index, group passes by tool.
    Append to the previous block when the tool matches; otherwise start a new one.
    This preserves each part's internal operation order while merging identical
    consecutive tools across parts.
    """
    max_passes = max((len(p.part.passes) for p in placements), default=0)
    blocks: list = []

    for idx in range(max_passes):
        by_tool: Dict[str, list] = {}
        for placed in placements:
            if idx < len(placed.part.passes):
                gp = placed.part.passes[idx]
                by_tool.setdefault(gp.tool_number, []).append((placed, gp.lines))

        for tool in sorted(by_tool):
            segs: list = []
            description = ""
            spindle_speed = 18000

            for placed, raw_lines in by_tool[tool]:
                if not description:
                    description = _tool_comment(raw_lines)
                spd = _spindle_speed(raw_lines)
                if spd:
                    spindle_speed = spd
                body = _extract_body(raw_lines)
                params = _transform_params(placed, rail_w, bed_x)
                segs.append([_transform_line(ln, params) for ln in body])

            if blocks and blocks[-1]["tool"] == tool:
                blocks[-1]["segments"].extend(segs)
            else:
                blocks.append({
                    "tool": tool,
                    "description": description,
                    "spindle_speed": spindle_speed,
                    "segments": segs,
                })

    return blocks


# ── pass helpers ──────────────────────────────────────────────────────────────

def _tool_comment(lines: List[str]) -> str:
    for line in lines:
        m = _TOOL_CMT.search(line)
        if m:
            return m.group(1).strip()
    return ""


def _spindle_speed(lines: List[str]) -> Optional[int]:
    for line in lines:
        m = _SPINDLE.search(line)
        if m:
            return int(m.group(1))
    return None


def _extract_body(lines: List[str]) -> List[str]:
    """
    Return the movement lines from a pass: everything after M03 and before
    the trailing G53/M05/M30 retract block. Strips any existing N-codes.
    """
    body: List[str] = []
    in_body = False
    for line in lines:
        s = line.strip()
        if not in_body:
            if re.search(r"\bM03\b", s, re.IGNORECASE):
                in_body = True
        else:
            if (s == "%" or
                    re.search(r"\bM05\b|\bM30\b", s, re.IGNORECASE) or
                    (re.search(r"\bG53\b", s, re.IGNORECASE) and "Z" in s.upper())):
                break
            if s:
                body.append(_N_CODE.sub("", s))
    return body


# ── coordinate transformation ─────────────────────────────────────────────────

def _transform_params(placed: PlacedPart, rail_w: float, bed_x: float) -> dict:
    """
    Pre-compute per-placement transform constants.

    VCarve X → G-code X output → machine Y direction
    VCarve Y → G-code Y output → machine X direction

    A rail (translate, mirror X only):
      output_X = slot_mark - vcarve_X        (G-code X = machine Y, reversed)
      output_Y = rail_w + vcarve_Y           (G-code Y = machine X, additive)

    B rail (mirror both):
      output_X = (slot_mark + vcarve_x_span) - vcarve_X
      output_Y = (bed_x - rail_w) - vcarve_Y
    """
    slot_mark = (120.0 - placed.slot_inches) * 25.4
    if placed.rail == "A":
        return {"b_x": True,  "x": slot_mark,
                "b_y": False, "y": rail_w}
    return {"b_x": True, "x": slot_mark + placed.part.vcarve_x_span,
            "b_y": True, "y": bed_x - rail_w}


def _transform_line(line: str, p: dict) -> str:
    """
    Apply placement transform to XY coordinates on one G-code line.

    Comments and G53 machine-coord lines are returned unchanged.

    A rail (b_x=True, b_y=False): mirror X only → swap G02/G03, negate I, keep J.
    B rail (b_x=True, b_y=True):  mirror both  → keep G02/G03, negate I and J.
    """
    s = line.strip()
    if not s or s.startswith("("):
        return s
    if re.search(r"\bG53\b", s, re.IGNORECASE):
        return s

    result = s
    x_mirror = p["b_x"]
    y_mirror = p["b_y"]

    # Arc direction: swap G02/G03 only when exactly one axis is mirrored
    if x_mirror != y_mirror:
        if re.search(r"\bG02\b", result, re.IGNORECASE):
            result = re.sub(r"\bG02\b", "G03", result, flags=re.IGNORECASE)
        elif re.search(r"\bG03\b", result, re.IGNORECASE):
            result = re.sub(r"\bG03\b", "G02", result, flags=re.IGNORECASE)

    # Arc centre offsets: negate I when X is mirrored, negate J when Y is mirrored
    if x_mirror:
        result = re.sub(r"(I)([+-]?\d*\.?\d+)",
                        lambda m: f"I{-float(m.group(2)):.4f}", result)
    if y_mirror:
        result = re.sub(r"(J)([+-]?\d*\.?\d+)",
                        lambda m: f"J{-float(m.group(2)):.4f}", result)

    def _repl_x(m: re.Match) -> str:
        val = float(m.group(1))
        return f"X{p['x'] - val:.4f}" if x_mirror else f"X{val + p['x']:.4f}"

    def _repl_y(m: re.Match) -> str:
        val = float(m.group(1))
        return f"Y{p['y'] - val:.4f}" if y_mirror else f"Y{val + p['y']:.4f}"

    result = re.sub(r"X([+-]?\d*\.?\d+)", _repl_x, result)
    result = re.sub(r"Y([+-]?\d*\.?\d+)", _repl_y, result)
    return result


# ── nearest-neighbour travel sort ─────────────────────────────────────────────

def _first_xy(lines: List[str]) -> Tuple[float, float]:
    x = y = None
    for line in lines:
        for axis, val in re.findall(r"([XY])([+-]?\d*\.?\d+)", line):
            if axis == "X" and x is None:
                x = float(val)
            elif axis == "Y" and y is None:
                y = float(val)
        if x is not None and y is not None:
            break
    return (x or 0.0, y or 0.0)


def _last_xy(lines: List[str]) -> Tuple[float, float]:
    return _first_xy(list(reversed(lines)))


def _nearest_neighbor_sort(segs: list) -> list:
    """Greedy nearest-neighbour ordering to minimise rapid travel between segments."""
    if len(segs) <= 1:
        return segs
    remaining = list(segs)
    result = [remaining.pop(0)]
    last = _last_xy(result[0])
    while remaining:
        best_i, best_d = 0, float("inf")
        for i, seg in enumerate(remaining):
            dx, dy = _first_xy(seg)[0] - last[0], _first_xy(seg)[1] - last[1]
            d = (dx * dx + dy * dy) ** 0.5
            if d < best_d:
                best_d, best_i = d, i
        result.append(remaining.pop(best_i))
        last = _last_xy(result[-1])
    return result
