from typing import List, Dict


def generate_master_gcode(parts: List[Dict], settings: Dict) -> str:
    """Generate a placeholder master G-code string for placed parts."""
    header = [
        "(MASTER JOB - Generated by 5x10 CNC Layout Tool)",
        "(Date: TODO)",
        "(Job: TODO)",
    ]
    body = ["M30"]
    return "\n".join(header + ["", *body])
